import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/src/globals.css";
import Navigation from "@/src/components/Navigation";
import Footer from "@/src/components/Footer";
import { locales } from "@/src/config";
import { unstable_setRequestLocale } from "next-intl/server";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trivia | Random Fun Trivia!",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  unstable_setRequestLocale(locale);

  return (
    <html lang={locale}>
      <body className={clsx(inter.className, "min-h-screen")}>
        <Navigation />
        {children}
        <Footer params={{ locale }} />
      </body>
    </html>
  );
}
